DEEPLEARNING_REFINE_MASK:
  USE_MASK_REFINE: true
  MODEL_PATH: checkpoints/MGMatting-RWP-100k/latest_model.pth
  POST_PROCESS: true
GRAY_SCALE: true
USE_BKC_REPLACE: true
BACKGROUND_COLOR_RGB:
- 255
- 255
- 255
DATA_OUT: data_out
